#ifndef doublebox_nonplanar_integral_codegen_contour_deformation_sector_2_order_0_hpp_included
#define doublebox_nonplanar_integral_codegen_contour_deformation_sector_2_order_0_hpp_included
#include "doublebox_nonplanar_integral.hpp"
#include "functions.hpp"
namespace doublebox_nonplanar_integral
{
secdecutil::SectorContainerWithDeformation<real_t, complex_t>::DeformedIntegrandFunction sector_2_order_0_contour_deformation_polynomial;
};
#endif
