#ifndef doublebox_nonplanar_integral_codegen_optimize_deformation_parameters_sector_5_order_0_hpp_included
#define doublebox_nonplanar_integral_codegen_optimize_deformation_parameters_sector_5_order_0_hpp_included
#include "doublebox_nonplanar_integral.hpp"
#include "functions.hpp"
#include <cmath>
#include <limits>
#include <vector>
namespace doublebox_nonplanar_integral
{
secdecutil::SectorContainerWithDeformation<real_t, complex_t>::MaximalDeformationFunction sector_5_order_0_maximal_allowed_deformation_parameters;
};
#endif
